services:
  - type: web
    name: karematch
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run db:push && npm run db:seed:full && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: ENCRYPTION_KEY
        sync: false
