CREATE TYPE "public"."admin_role" AS ENUM('admin', 'super_admin');--> statement-breakpoint
CREATE TYPE "public"."profile_status" AS ENUM('pending', 'approved', 'rejected', 'inactive');--> statement-breakpoint
CREATE TABLE "admin_users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"role" "admin_role" DEFAULT 'admin' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "admin_users_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "therapists" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"profile_status" "profile_status" DEFAULT 'pending' NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"credentials" text,
	"photo_url" text,
	"pronouns" text,
	"languages_spoken" text[] DEFAULT ARRAY[]::text[],
	"email" text NOT NULL,
	"phone" text,
	"website" text,
	"practice_name" text,
	"street_address" text,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"zip_code" text NOT NULL,
	"country" text DEFAULT 'USA',
	"latitude" numeric,
	"longitude" numeric,
	"license_type" text,
	"license_number" text NOT NULL,
	"license_state" text NOT NULL,
	"npi_number" text,
	"years_in_practice" integer,
	"graduate_school" text,
	"graduation_year" integer,
	"bio" text,
	"therapeutic_approach" text,
	"session_types" text[] DEFAULT ARRAY[]::text[],
	"modalities" text[] DEFAULT ARRAY[]::text[],
	"accepting_new_clients" boolean DEFAULT true,
	"top_specialties" text[] DEFAULT ARRAY[]::text[],
	"issues_treated" text[] DEFAULT ARRAY[]::text[],
	"communities_served" text[] DEFAULT ARRAY[]::text[],
	"age_groups" text[] DEFAULT ARRAY[]::text[],
	"therapy_types" text[] DEFAULT ARRAY[]::text[],
	"treatment_orientation" text,
	"individual_session_fee" integer,
	"couples_session_fee" integer,
	"offers_sliding_scale" boolean DEFAULT false,
	"sliding_scale_min" integer,
	"insurance_accepted" text[] DEFAULT ARRAY[]::text[],
	"payment_methods" text[] DEFAULT ARRAY[]::text[],
	"available_days" text[] DEFAULT ARRAY[]::text[],
	"available_times" text[] DEFAULT ARRAY[]::text[],
	"waitlist_status" boolean DEFAULT false,
	"video_intro_url" text,
	"profile_views" integer DEFAULT 0,
	"last_login" timestamp,
	CONSTRAINT "therapists_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"password" text NOT NULL,
	"role" text DEFAULT 'therapist' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
